### PR TITLE
better exit handling

### PR DESCRIPTION
**Pull request by renanbr**
- removed `exit()` calls
- added constants for exit codes

### CODE REVIEW

**Comment by theseer** [comment]
Thank you :-).
I already considered that approach as well (see branch "exitcodes") but wasn't fully happy with it as of yet since the errorHandler in my branch still required the exit call. Your PR simply removes it. 

I'm not convinced that's going to work as it will keep the application running rather than stopping execution on unexpected and otherwise unhandeled exceptions.

I also fail to see the use/usage of the lastException? What is the getter for and where do we use it?

**Comment by renanbr** [comment]
I've not seen the branch "exitcodes", sorry, so actually there is nothing new in my PR :-) somehow the approach is similar. Let me gather some ideas.

First of all, the cli api is fine, I would change nothing about it. Suppressing exit calls is for making possible  to call `CLI:run()` manually and to keep going when an error occurs.

> I'm not convinced that's going to work as it will keep the application running rather than stopping execution on unexpected and otherwise unhandeled exceptions.

When someone (like me) makes calls to the `CLI::run()` multiple times, so keep running is an expected behavior, then he/she may skip to the next calling if he/she wants to (note that I'm not talking about unhandled exceptions).

> I also fail to see the use/usage of the lastException? What is the getter for and where do we use it?

When `CLI::run()` returns some error code I would like to touch the exception object rather than to check output buffer.

**Comment by renanbr** [comment]
closing issue in favor of [exitcodes](https://github.com/theseer/phpdox/tree/exitcodes) branch

**Comment by theseer** [comment]
I do get your point and since we had the same idea for the exit codes, I guess that's a go.

What's missing is basically a better / alternative way for the exception handling. I guess i can simply work around that issue by making the error handler an interface and have it injected. That way you could use whatever mechanism you feel like when using the CLI class.

I'll ponder that and maybe adjust the exitcode branch accordingly. I start to like that idea :)

**Comment by theseer** [comment]
Come to think o fit, there shouldn't be any practical chance for the fallback exception handler to be triggered as the CLI will catch \Exception and thus no "uncaught exception" should get through.

I thus adopted your idea to remove the exit from the exception handling and also added some more exit codes.

**Comment by theseer** [comment]
Further discussion, if need be, should happen in #186

**Pull request closed without merging**
