### PR TITLE
Tweaked phpdoc line parser regex to accept single line docblock

### PR DESCRIPTION
**Pull request by gandazgul**
e.g. /** @var Type */

### CODE REVIEW

**Comment by gandazgul** [comment]
That build didn't actually failed, something weird happend with Travis it built twice for the same php versions, one passed one failed.

**Comment by theseer** [comment]
Looks good. I'll try to merge it later today or tomorrow.

**Comment by gandazgul** [comment]
Thank you

**Comment by gandazgul** [comment]
Hi @theseer did you have some time to merge this in? 

Thanks

**Comment by theseer** [comment]
Merged locally.

**Pull request closed without merging**
