### PR TITLE
Link from Namespaces to Classes for that Namespace

### PR DESCRIPTION
**Pull request by soundasleep**

### CODE REVIEW

**Comment by theseer** [comment]
While it looks like a good idea at first, the link target on the namespace name is ambiguous:
Why would the target be the classes while there are (potentially) interfaces and traits as well? And what happens if said namespace does not contain any class but only interfaces or traits?

I thus only placed links on the individual counters, directing to classes, interfaces or traits respectively.

**Comment by soundasleep** [comment]
It does mean that there's a very small click target on the Namespaces page, especially if there's only a few classes in a namespace - in my experience most namespaces have classes, rather than interfaces or traits, so defaulting to linking to classes seems a nice usability improvement.

**Comment by theseer** [comment]
We could potentially make that a CSS menu  based menu to choose where to jump to?

**Comment by soundasleep** [comment]
That's probably adding too much complexity. Maybe if there are no classes for a namespace, don't generate a link, otherwise link through to the classes for that namespace?

**Comment by theseer** [comment]
That's inconsistent behavior. It looks like the world is telling me / us, that the page should be redesigned ;)

**Pull request closed without merging**
